version: '2'
services:
  vradar-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/vradar/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vradar
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
